services:
  - type: web
    name: mfa-vexpex-api
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
